In [15]:
import torch
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(2,2,device=device,requires_grad=True)
  
  print(x)
  
  y = x + 2
  print(y)
  print(y.grad_fn) # y = 연산의 결과
  
  z = y * y * 3
  
  out = z.mean()
  
  print(z, out)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0', requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], device='cuda:0', grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], device='cuda:0', grad_fn=<MulBackward0>) tensor(27., device='cuda:0', grad_fn=<MeanBackward0>)


In [20]:
  a = torch.randn(2,2,device= device)
  a = ((a*3)/(a-1))
  print(a.requires_grad)
  a.requires_grad_(True)
  print(a.requires_grad)
  b = (a*a).sum()
  print(b.grad_fn)
  

False
True
